version: '2.0'

services:
  producer:
    image: danspaes/scala-slim
    ports: 
      - "10171:10171"
    container_name: producer
    hostname: producer
    depends_on: 
      - kafka 
    networks:
      net:
        ipv4_address: 171.69.1.2
    expose:
      - "10171"
    volumes: 
      - ./producer:/opt/producer
    entrypoint: ["sh", "/opt/producer/launch_producer.sh"]
    restart: always
  
  consumer:
    image: danspaes/spark-slim
    container_name: consumer
    hostname: consumer
    environment:
      - "SPARK_MASTER_PORT=7077"
      - "SPARK_MASTER_WEBUI_PORT=8080"
    command: spark-class org.apache.spark.deploy.master.Master
    networks:
      net:
        ipv4_address: 171.69.1.3
    depends_on: 
      - kafka 
    ports: 
      - "4040:4040"
      - "7077:7077"
      - "8080:8080"
      - "6066:6066"

    expose: 
      - "4040"
      - "7077"
      - "8080"
      - "6066"
    volumes: 
      - ./consumer:/opt/consumer
      - ./data:/tmp/data


  worker:
    image: danspaes/spark-slim
    container_name: worker
    depends_on:
      - consumer
    command: spark-class org.apache.spark.deploy.worker.Worker spark://171.69.1.3:7077
    ports:
      - "8081:8081"
    environment:
      - "SPARK_CONF_DIR=/conf"
      - "SPARK_WORKER_CORES=4"
      - "SPARK_WORKER_MEMORY=2g"
      - "SPARK_WORKER_PORT=8881"
      - "SPARK_WORKER_WEBUI_PORT=8081"
    extra_hosts:
      - "consumer:171.69.1.3"
    ports: 
      - "8081"
    networks:
      net:
    volumes:
      - ./data:/tmp/data

  kafka:
    image: spotify/kafka
    ports:
      - "9092:9092"
      - "2181:2181"
    container_name: kafka
    hostname: kafka
    networks:
      net:
        ipv4_address: 171.69.1.4
    expose:
      - "9092"
      - "2181"
    environment:
      ADVERTISED_HOST: 171.69.1.4
      ADVERTISED_PORT: 9092
      AUTO_CREATE_TOPICS: "false" 
      DELETE_TOPIC_ENABLE: "true" 
    command: >
      bash -c
      "(sleep 15s &&
      /opt/kafka_2.11-0.10.1.0/bin/kafka-topics.sh
      --create
      --zookeeper
      localhost:2181 --replication-factor 1 --partitions 1
      --topic stocks &) && (supervisord -n)"
    
    restart: always

networks:
    net:
        ipam:
            driver: default
            config:
                - subnet: 171.69.0.0/16
